---
version: 5
defaults:
  datadir: "/etc/puppetlabs/code/environments/%{environment}/hiera"
  data_hash: yaml_data

:hierarchy:
  - name: "Per-node data"
    path: "nodes/%{::fqdn}.yaml"

  - name: "type data"
    path: "virtual/%{::is_virtual}.yaml"

  - name: "os data"
    path: "os/%{::facts.os.family}/%{::facts.os.distro.codename}.yaml"

  - name: "environment data"
    path: "environment/%{::environment}.yaml"

  - name: "Common data"
    path: "common.yaml"
